#[test_only]
module mmr::mmr_proof_tests;

use std::unit_test::assert_eq;
use mmr::mmr_proof;
use mmr::mmr_prover::{Self, NodeSet};
use mmr::mmr_utils;

// Golden values (blake2b-256; regenerated by scripts/golden.py, spec H.2).
const ROOT_0: vector<u8> = x"0fd923ca5e7218c4ba3c3801c26a617ecdbfdaebb9c76ce2eca166e7855efbb8";
const ROOT_1: vector<u8> = x"d6c34429feff433582703182c426f2143b1d191d41bcac91b8f88a8ea2785339";
const ROOT_2: vector<u8> = x"297edbfdc015ad4528d9f9e2fc245c624910f16677cb2b281dfb413d3751b929";
const ROOT_3: vector<u8> = x"768ab1c59f5bef49e8b35a1af43caeefb13073e2547cc65e300c174c198a0f8c";
const ROOT_4: vector<u8> = x"3e963f084c975b07bb7a752ea7cb475300247a89178d04f592c5d8c1d9827bec";
const ROOT_7: vector<u8> = x"38f62b6e543c713b10c89be1b3d0e3789739c95f576b22627b552da09562a0b6";
const ROOT_8: vector<u8> = x"8074453634fa4d8a79c73484842c2b1ddc6730961d2465d751cdce04d6e7f996";
const ROOT_13: vector<u8> = x"737ff3b5d4244e05bc4248b78002040f3d9e37a55fcdea39a57d955cdb5e79d5";
const ROOT_95: vector<u8> = x"58cd048bbf551d2b2ca2f72360c1f9a51b1b4eff9d694c236976096e1199ff91";
const ROOT_128: vector<u8> = x"15924c07e5974028531ab9a63eabe1a669262d6a42df9100d66424610aa10897";
const ROOT_200: vector<u8> = x"3ea208597cbcf2aef85dee4e7400b33dbd33fc74add83a625e89beaa1d3e476d";
const ROOT_255: vector<u8> = x"bb42c8fb601a4f0399a2595f4490954a77d397b3607bd8c1282403bec58f5814";
const ROOT_256: vector<u8> = x"36c40a5ef32cf15024408873fecc903cd8d59ffeba190ccb2d90475df99ed16d";
const ROOT_511: vector<u8> = x"34cda9a7467d484b25ce009f059ee55f818e1f931744a5bdc99e877e402d674b";
const ROOT_512: vector<u8> = x"918e88dc67110c35bf8eb9e125a0017c2567e11f1464962c9be15682d10c4dc8";
const ROOT_1000: vector<u8> = x"3bc88226da8e8fc7ec4d7571cc23d9de18e6eaa9667f9be06c2069bbce994de0";
const ROOT_1023: vector<u8> = x"2f1e9f5d75d7e40d2f6e443ad97307d0c02f362dfe797f734a3e9957d0de3fe2";
const ROOT_1024: vector<u8> = x"2129b7a87823f26eb74ade3f31926250fefa64f35015a56b4d7dd5fc57380ed5";

// README MMR (13 leaves, size 23) node hashes, `nX` = node at position X.
const N2: vector<u8> = x"823eb4e62aa79fe41b30978e8aa72109ef073083b204f0bab92dbb87ffd76da8";
const N3: vector<u8> = x"872e37e927e31aaafe7059839ac9e8899f6547e3635e22a5d7aa5fd853597fbf";
const N5: vector<u8> = x"f8e92a1d85d9c9cbe4b894e3bdd2a348fc0f2e6e7e4fe41439b8ed51d1d31581";
const N6: vector<u8> = x"ed72748d9781d4aecd1164c3f4d78e90d1bd6aa85d03847fac805a0bf48654a2";
const N8: vector<u8> = x"4ae022e3ec3a90f89aaf32c93f298d79b9522407afbd2b5b5da2fb9dae88ef06";
const N13: vector<u8> = x"e42613afcdfb3ff45b5ae0c636d9760eb5f1ba957dcf63116b8db53b357e32f4";
const N14: vector<u8> = x"479cb361e0bdc5e7ff92f131b65a808d09c5e26eef1104c903f0766985820fa6";
const N15: vector<u8> = x"8d2ffeca2d06c15af359441bc8292071f17c9aa820c62c33c4eca3955e060675";
const N17: vector<u8> = x"0144ea629dc1bd8fe6fc9eb51a8524b8e7529cbec44741bd020763e1a1377c63";
const N21: vector<u8> = x"a989072f2a74d648c1a53a036adc2af63e71d4d0ec3f604d4080a67146243f84";
const N22: vector<u8> = x"a31dba909c85ecc874b3eecb65ef46b08440b88f18126b9c6092874af7c95d69";
const N23: vector<u8> = x"fa4d80fd8386d9b5abaca7d1d5660a0255921013df1928b59501b8bd6d342772";

/// All 13 leaf positions of the README MMR.
const ALL_13: vector<u64> = vector[1, 2, 4, 5, 8, 9, 11, 12, 16, 17, 19, 20, 23];

// ------------------------------------------------------------------------------ helpers

/// True with the leaf's own data, false with the next leaf's data; the batch of one equals the
/// single proof (`siblings == path`, `untouched == left ++ right`) and verifies.
fun check_single(ns: &NodeSet, leaf_no: u64) {
    let position = mmr_prover::leaf_position(leaf_no);
    let (path, left, right) = ns.single_proof(position);
    let root = ns.root();
    let size = ns.size();
    assert!(mmr_proof::verify_with_root(root, size, position, mmr_prover::leaf_data(leaf_no), path, left, right));
    assert!(!mmr_proof::verify_with_root(root, size, position, mmr_prover::leaf_data(leaf_no + 1), path, left, right));
    let (siblings, untouched) = ns.batch_proof(vector[position]);
    assert_eq!(siblings, path);
    let mut expected_untouched = left;
    expected_untouched.append(right);
    assert_eq!(untouched, expected_untouched);
    assert!(mmr_proof::verify_multiple_with_root(root, size, vector[position], vector[mmr_prover::leaf_data(leaf_no)], siblings, untouched));
}

/// The batch proof of `leaf_numbers` verifies; one wrong leaf makes it false.
fun check_batch(ns: &NodeSet, leaf_numbers: vector<u64>) {
    let positions = leaf_numbers.map_ref!(|n| mmr_prover::leaf_position(*n));
    let leaves = leaf_numbers.map_ref!(|n| mmr_prover::leaf_data(*n));
    let (siblings, untouched) = ns.batch_proof(positions);
    assert!(mmr_proof::verify_multiple_with_root(ns.root(), ns.size(), positions, leaves, siblings, untouched));
    let mut bad = leaves;
    *(&mut bad[0]) = b"not the leaf";
    assert!(!mmr_proof::verify_multiple_with_root(ns.root(), ns.size(), positions, bad, siblings, untouched));
}

/// Independent count of the proof hashes a batch needs: the frontier of the union of the leaf
/// paths (siblings of ancestors that are neither batch leaves nor ancestors) plus the peaks of
/// the mountains no batch leaf touches. Port of `naive_multiproof_hash_count` (mmr_ref.py).
fun frontier_hash_count(size: u64, positions: &vector<u64>): u64 {
    let peaks = mmr_utils::get_peaks_positions(size);
    // membership bitmaps over positions 0..size (index 0 unused)
    let mut is_peak = vector::tabulate!(size + 1, |_| false);
    peaks.do_ref!(|p| *(&mut is_peak[*p]) = true);
    // ancestors of the batch leaves, the leaves themselves included
    let mut anc = vector[];
    let mut in_anc = vector::tabulate!(size + 1, |_| false);
    positions.do_ref!(|p| {
        let mut cur = *p;
        while (!is_peak[cur]) {
            if (!in_anc[cur]) { anc.push_back(cur); *(&mut in_anc[cur]) = true; };
            cur = mmr_utils::get_parent_position(cur);
        };
        if (!in_anc[cur]) { anc.push_back(cur); *(&mut in_anc[cur]) = true; };
    });
    // siblings of ancestors that are neither leaves nor ancestors must come from the proof
    let mut needed = 0;
    let mut in_needed = vector::tabulate!(size + 1, |_| false);
    anc.do_ref!(|a| {
        if (!is_peak[*a]) {
            let s = mmr_utils::get_sibling_position(*a);
            if (!in_anc[s] && !in_needed[s]) { needed = needed + 1; *(&mut in_needed[s]) = true; };
        };
    });
    let mut untouched = 0;
    peaks.do_ref!(|p| if (!in_anc[*p]) untouched = untouched + 1);
    needed + untouched
}

/// Copy of `hashes` with the first byte of entry `i` flipped.
fun flip(hashes: vector<vector<u8>>, i: u64): vector<vector<u8>> {
    let mut v = hashes;
    let byte = &mut v[i][0];
    *byte = *byte ^ 0x01;
    v
}

/// Copy of `hashes` with entries 0 and 1 swapped.
fun swap01(hashes: vector<vector<u8>>): vector<vector<u8>> {
    let mut v = hashes;
    v.swap(0, 1);
    v
}

/// Deterministic pseudo-random u64 (LCG in u128 arithmetic).
fun next(state: &mut u128): u64 {
    *state = ((*state * 6364136223846793005) + 1442695040888963407) % (1u128 << 64);
    (*state >> 33) as u64
}

// ------------------------------------------------------------------------------ golden vectors

#[test]
fun golden_roots() {
    assert_eq!(mmr_prover::build(0).root(), ROOT_0);
    assert_eq!(mmr_prover::build(1).root(), ROOT_1);
    assert_eq!(mmr_prover::build(2).root(), ROOT_2);
    assert_eq!(mmr_prover::build(3).root(), ROOT_3);
    assert_eq!(mmr_prover::build(4).root(), ROOT_4);
    assert_eq!(mmr_prover::build(7).root(), ROOT_7);
    assert_eq!(mmr_prover::build(8).root(), ROOT_8);
    let ns13 = mmr_prover::build(13);
    assert_eq!(ns13.size(), 23);
    assert_eq!(ns13.leaf_count(), 13);
    assert_eq!(ns13.peaks(), vector[N15, N22, N23]);
    assert_eq!(ns13.root(), ROOT_13);
    assert_eq!(mmr_prover::build(95).root(), ROOT_95);
    assert_eq!(mmr_prover::build(128).root(), ROOT_128);
    assert_eq!(mmr_prover::build(200).root(), ROOT_200);
}

#[test]
fun golden_roots_large() {
    assert_eq!(mmr_prover::build(255).root(), ROOT_255);
    assert_eq!(mmr_prover::build(256).root(), ROOT_256);
}

#[test]
fun golden_roots_511() {
    assert_eq!(mmr_prover::build(511).root(), ROOT_511);
}

#[test]
fun golden_roots_512() {
    assert_eq!(mmr_prover::build(512).root(), ROOT_512);
}

// The three largest H.2 roots: each build alone is about 3M units, so one per test.
#[test]
fun golden_roots_1000() {
    let ns = mmr_prover::build(1000);
    assert_eq!(ns.size(), 1994);
    assert_eq!(ns.root(), ROOT_1000);
}

#[test]
fun golden_roots_1023() {
    let ns = mmr_prover::build(1023);
    assert_eq!(ns.size(), 2036);
    assert_eq!(ns.root(), ROOT_1023);
}

#[test]
fun golden_roots_1024() {
    let ns = mmr_prover::build(1024);
    assert_eq!(ns.size(), 2047);
    assert_eq!(ns.root(), ROOT_1024);
}

#[test]
fun readme_proof_for_position_16() {
    let ns = mmr_prover::build(13);
    let (path, left, right) = ns.single_proof(16);
    assert_eq!(path, vector[N17, N21]);
    assert_eq!(left, vector[N15]);
    assert_eq!(right, vector[N23]);
    assert!(mmr_proof::verify_with_root(ROOT_13, 23, 16, b"9", path, left, right));
    assert!(!mmr_proof::verify_with_root(ROOT_13, 23, 16, b"8", path, left, right));
}

#[test]
fun worked_batch_examples() {
    let ns = mmr_prover::build(13);
    // {1}
    let (s, u) = ns.batch_proof(vector[1]);
    assert_eq!(s, vector[N2, N6, N14]);
    assert_eq!(u, vector[N22, N23]);
    assert!(mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[1], vector[b"1"], s, u));
    // {16} == the README single proof: path [n17, n21], left [n15], right [n23]
    let (s, u) = ns.batch_proof(vector[16]);
    assert_eq!(s, vector[N17, N21]);
    assert_eq!(u, vector[N15, N23]);
    assert!(mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[16], vector[b"9"], s, u));
    // {1, 2}: the sibling leaf is derived, nothing is read for it
    let (s, u) = ns.batch_proof(vector[1, 2]);
    assert_eq!(s, vector[N6, N14]);
    assert_eq!(u, vector[N22, N23]);
    assert!(mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[1, 2], vector[b"1", b"2"], s, u));
    // {4, 9, 16}: siblings in (height, position) order per mountain (n3 after n8)
    let (siblings, untouched) = ns.batch_proof(vector[4, 9, 16]);
    assert_eq!(siblings, vector[N5, N8, N3, N13, N17, N21]);
    assert_eq!(untouched, vector[N23]);
    let leaves = vector[b"3", b"6", b"9"];
    assert!(mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[4, 9, 16], leaves, siblings, untouched));
    // position-sorted sibling order is wrong
    let wrong_order = vector[N3, N5, N8, N13, N17, N21];
    assert!(!mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[4, 9, 16], leaves, wrong_order, untouched));
    // {23}: a leaf that is a peak
    let (s, u) = ns.batch_proof(vector[23]);
    assert_eq!(s, vector[]);
    assert_eq!(u, vector[N15, N22]);
    assert!(mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[23], vector[b"13"], s, u));
    // all leaves: no proof hashes at all
    let (s, u) = ns.batch_proof(ALL_13);
    assert_eq!(s, vector[]);
    assert_eq!(u, vector[]);
    assert!(mmr_proof::verify_multiple_with_root(ROOT_13, 23, ALL_13, mmr_prover::leaves(13), s, u));
}

#[test]
fun compute_root_matches_verify() {
    let ns = mmr_prover::build(13);
    let (path, left, right) = ns.single_proof(16);
    assert_eq!(mmr_proof::compute_root(23, 16, b"9", path, left, right), ROOT_13);
    assert!(mmr_proof::compute_root(23, 16, b"8", path, left, right) != ROOT_13);
    let (siblings, untouched) = ns.batch_proof(vector[4, 9, 16]);
    let leaves = vector[b"3", b"6", b"9"];
    assert_eq!(mmr_proof::compute_batch_root(23, vector[4, 9, 16], leaves, siblings, untouched), ROOT_13);
}

/// A proof of one MMR never verifies against the root of another MMR of the same shape, and
/// the other MMR's honest proof verifies only against its own root.
#[test]
fun proofs_are_bound_to_their_anchor() {
    let ns13 = mmr_prover::build(13);
    let (path, left, right) = ns13.single_proof(16);
    // another 13-leaf MMR with different data ("1!".."13!"): same shape, different root
    let mut other = mmr_prover::new();
    other.append_all(vector::tabulate!(13, |i| { let mut d = mmr_prover::leaf_data(i + 1); d.push_back(33); d }));
    assert_eq!(other.size(), 23);
    assert!(other.root() != ROOT_13);
    assert!(!mmr_proof::verify_with_root(other.root(), 23, 16, b"9", path, left, right));
    let (path2, left2, right2) = other.single_proof(16);
    assert!(mmr_proof::verify_with_root(other.root(), 23, 16, b"9!", path2, left2, right2));
    assert!(!mmr_proof::verify_with_root(ROOT_13, 23, 16, b"9!", path2, left2, right2));
    assert!(!mmr_proof::verify_with_root(ROOT_13, 23, 16, b"9", path2, left2, right2));
}

// ------------------------------------------------------------------------------ exhaustive single
// One #[test] per chunk: the unit-test meter caps every test at about 5M computation units.

fun check_leaf_range(n: u64, from: u64, to: u64) {
    let ns = mmr_prover::build(n);
    let mut leaf_no = from;
    while (leaf_no <= to) { check_single(&ns, leaf_no); leaf_no = leaf_no + 1; };
}

#[test] fun every_leaf_13() { check_leaf_range(13, 1, 13); }
#[test] fun every_leaf_95_a() { check_leaf_range(95, 1, 24); }
#[test] fun every_leaf_95_b() { check_leaf_range(95, 25, 48); }
#[test] fun every_leaf_95_c() { check_leaf_range(95, 49, 72); }
#[test] fun every_leaf_95_d() { check_leaf_range(95, 73, 95); }
#[test] fun every_leaf_200_a() { check_leaf_range(200, 1, 20); }
#[test] fun every_leaf_200_b() { check_leaf_range(200, 21, 40); }
#[test] fun every_leaf_200_c() { check_leaf_range(200, 41, 60); }
#[test] fun every_leaf_200_d() { check_leaf_range(200, 61, 80); }
#[test] fun every_leaf_200_e() { check_leaf_range(200, 81, 100); }
#[test] fun every_leaf_200_f() { check_leaf_range(200, 101, 120); }
#[test] fun every_leaf_200_g() { check_leaf_range(200, 121, 140); }
#[test] fun every_leaf_200_h() { check_leaf_range(200, 141, 160); }
#[test] fun every_leaf_200_i() { check_leaf_range(200, 161, 180); }
#[test] fun every_leaf_200_j() { check_leaf_range(200, 181, 200); }

// 1000 leaves: a deterministic 65-leaf sample, at most 5 leaves per test (the build alone is
// about 2.9M units and a deep leaf about 210K; chunks of 10 exceed the 5M meter).
// scripts/mmr_ref.py self-check sweeps all 1000 leaves; this sample keeps coverage runs practical.
// The leaf numbers cover every mountain shape (2^k - 1, 2^k, 2^k + 1 up to 513, then 999, 1000)
// plus the stride 26, 52, ..., 962.
fun check_leaves_1000(leaf_numbers: vector<u64>) {
    let ns = mmr_prover::build(1000);
    leaf_numbers.do!(|leaf_no| check_single(&ns, leaf_no));
}

#[test] fun every_leaf_1000_a() { check_leaves_1000(vector[1, 2, 3, 4, 5]); }
#[test] fun every_leaf_1000_b() { check_leaves_1000(vector[8, 9, 15, 16, 17]); }
#[test] fun every_leaf_1000_c() { check_leaves_1000(vector[26, 31, 32, 33, 52]); }
#[test] fun every_leaf_1000_d() { check_leaves_1000(vector[63, 64, 65, 78, 104]); }
#[test] fun every_leaf_1000_e() { check_leaves_1000(vector[127, 128, 129, 130, 156]); }
#[test] fun every_leaf_1000_f() { check_leaves_1000(vector[182, 208, 234, 255, 256]); }
#[test] fun every_leaf_1000_g() { check_leaves_1000(vector[257, 260, 286, 312, 338]); }
#[test] fun every_leaf_1000_h() { check_leaves_1000(vector[364, 390, 416, 442, 468]); }
#[test] fun every_leaf_1000_i() { check_leaves_1000(vector[494, 511, 512, 513, 520]); }
#[test] fun every_leaf_1000_j() { check_leaves_1000(vector[546, 572, 598, 624, 650]); }
#[test] fun every_leaf_1000_k() { check_leaves_1000(vector[676, 702, 728, 754, 780]); }
#[test] fun every_leaf_1000_l() { check_leaves_1000(vector[806, 832, 858, 884, 910]); }
#[test] fun every_leaf_1000_m() { check_leaves_1000(vector[7, 936, 962, 999, 1000]); }

// ------------------------------------------------------------------------------ exhaustive subsets

/// Every subset of the leaves of an n-leaf MMR whose bitmask lies in [from_mask, to_mask].
fun check_subsets(n: u64, from_mask: u64, to_mask: u64) {
    let ns = mmr_prover::build(n);
    let mut mask = from_mask;
    while (mask <= to_mask) {
        let mut leaf_numbers = vector[];
        n.do!(|i| if ((mask >> (i as u8)) & 1 == 1) leaf_numbers.push_back(i + 1));
        check_batch(&ns, leaf_numbers);
        mask = mask + 1;
    };
}

// all 502 non-empty subsets for 1..=8 leaves
#[test] fun every_subset_1_to_5_leaves() { 5u64.do!(|k| check_subsets(k + 1, 1, (1 << ((k + 1) as u8)) - 1)); }
#[test] fun every_subset_6_leaves() { check_subsets(6, 1, 63); }
#[test] fun every_subset_7_leaves() { check_subsets(7, 1, 127); }
#[test] fun every_subset_8_leaves_a() { check_subsets(8, 1, 127); }
#[test] fun every_subset_8_leaves_b() { check_subsets(8, 128, 255); }

/// `count` pseudo-random subsets (about one leaf in seven) of an n-leaf MMR, after skipping the
/// first `skip` subsets of the same LCG stream. Every proof size equals the independent frontier
/// count.
fun check_random_subsets(n: u64, seed: u128, skip: u64, count: u64) {
    let ns = mmr_prover::build(n);
    let mut state = seed;
    skip.do!(|_| n.do!(|_| { next(&mut state); }));
    count.do!(|_| {
        let mut leaf_numbers = vector[];
        n.do!(|i| if (next(&mut state) % 7 == 0) leaf_numbers.push_back(i + 1));
        if (leaf_numbers.is_empty()) leaf_numbers.push_back(1);
        let positions = leaf_numbers.map_ref!(|l| mmr_prover::leaf_position(*l));
        let leaves = leaf_numbers.map_ref!(|l| mmr_prover::leaf_data(*l));
        let (siblings, untouched) = ns.batch_proof(positions);
        assert!(mmr_proof::verify_multiple_with_root(ns.root(), ns.size(), positions, leaves, siblings, untouched));
        let mut bad = leaves;
        *(&mut bad[0]) = b"not the leaf";
        assert!(!mmr_proof::verify_multiple_with_root(ns.root(), ns.size(), positions, bad, siblings, untouched));
        assert_eq!(siblings.length() + untouched.length(), frontier_hash_count(ns.size(), &positions));
    });
}

// seeds 7 / 11 / 13; 12 + 6 + 6 batches (the 200-leaf seeds are split in two chunks each)
#[test] fun random_subsets_95() { check_random_subsets(95, 7, 0, 12); }
#[test] fun random_subsets_200_a() { check_random_subsets(200, 11, 0, 3); }
#[test] fun random_subsets_200_b() { check_random_subsets(200, 13, 0, 3); }
#[test] fun random_subsets_200_c() { check_random_subsets(200, 11, 3, 3); }
#[test] fun random_subsets_200_d() { check_random_subsets(200, 13, 3, 3); }

/// Batch checks for strictly increasing leaf `positions` of the "1".."n" fixture: the proof
/// verifies, its size equals the independent frontier count, `compute_batch_root` agrees, and a
/// wrong leaf at `wrong_index` makes it false.
fun check_batch_positions(ns: &NodeSet, positions: vector<u64>, wrong_index: u64) {
    let root = ns.root();
    let size = ns.size();
    let leaves = positions.map_ref!(|p| mmr_prover::leaf_data(mmr_utils::position_to_leaf_index(*p) + 1));
    let (siblings, untouched) = ns.batch_proof(positions);
    assert_eq!(siblings.length() + untouched.length(), frontier_hash_count(size, &positions));
    assert!(mmr_proof::verify_multiple_with_root(root, size, positions, leaves, siblings, untouched));
    assert_eq!(mmr_proof::compute_batch_root(size, positions, leaves, siblings, untouched), root);
    let mut wrong = leaves;
    *(&mut wrong[wrong_index]) = b"x";
    assert!(!mmr_proof::verify_multiple_with_root(root, size, positions, wrong, siblings, untouched));
}

/// Batches that touch every mountain shape of the README MMR: a whole mountain, one leaf per
/// mountain, the two peak neighbours, and adjacent pairs across mountain borders.
#[test]
fun structured_batches_13() {
    let ns = mmr_prover::build(13);
    check_batch_positions(&ns, vector[1, 2, 4, 5, 8, 9, 11, 12], 3);
    check_batch_positions(&ns, vector[16, 17, 19, 20], 0);
    check_batch_positions(&ns, vector[1, 16, 23], 1);
    check_batch_positions(&ns, vector[12, 16], 0);
    check_batch_positions(&ns, vector[20, 23], 1);
    check_batch_positions(&ns, vector[1, 23], 0);
    check_batch_positions(&ns, vector[2, 5, 9, 12, 17, 20], 5);
    check_batch_positions(&ns, vector[1, 4, 8, 11, 16, 19, 23], 6);
}

// ------------------------------------------------------------------------------ tamper (false)

#[test]
fun tampered_single_proofs_are_false() {
    let ns = mmr_prover::build(13);
    let root = ns.root();
    13u64.do!(|i| {
        let position = mmr_prover::leaf_position(i + 1);
        let data = mmr_prover::leaf_data(i + 1);
        let (path, left, right) = ns.single_proof(position);
        path.length().do!(|j| assert!(!mmr_proof::verify_with_root(root, 23, position, data, flip(path, j), left, right)));
        left.length().do!(|j| assert!(!mmr_proof::verify_with_root(root, 23, position, data, path, flip(left, j), right)));
        right.length().do!(|j| assert!(!mmr_proof::verify_with_root(root, 23, position, data, path, left, flip(right, j))));
        assert!(!mmr_proof::verify_with_root(flip(vector[root], 0)[0], 23, position, data, path, left, right));
        if (path.length() >= 2) {
            assert!(!mmr_proof::verify_with_root(root, 23, position, data, swap01(path), left, right));
        };
        // the same proof moved to the sibling leaf position (same shape, wrong position);
        // a leaf that is a peak (empty path) has no sibling
        if (path.length() > 0) {
            let sibling = mmr_utils::get_sibling_position(position);
            assert!(!mmr_proof::verify_with_root(root, 23, sibling, data, path, left, right));
        };
    });
}

#[test]
fun tampered_batch_proofs_are_false() {
    let ns = mmr_prover::build(13);
    let positions = vector[4, 9, 16];
    let leaves = vector[b"3", b"6", b"9"];
    let (siblings, untouched) = ns.batch_proof(positions);
    siblings.length().do!(|j| assert!(!mmr_proof::verify_multiple_with_root(ROOT_13, 23, positions, leaves, flip(siblings, j), untouched)));
    assert!(!mmr_proof::verify_multiple_with_root(ROOT_13, 23, positions, leaves, siblings, flip(untouched, 0)));
    // proof moved to a different (valid) leaf set with the same hashes -> false
    assert!(!mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[5, 9, 16], leaves, siblings, untouched));
}

// ------------------------------------------------------------------------------ aborts (single)

#[test, expected_failure(abort_code = mmr_proof::EInvalidSize)]
fun single_rejects_invalid_size() {
    mmr_proof::verify_with_root(ROOT_13, 24, 1, b"1", vector[], vector[], vector[]);
}

#[test, expected_failure(abort_code = mmr_proof::EPositionOutOfRange)]
fun single_rejects_position_zero() {
    mmr_proof::verify_with_root(ROOT_13, 23, 0, b"1", vector[], vector[], vector[]);
}

#[test, expected_failure(abort_code = mmr_proof::EPositionOutOfRange)]
fun single_rejects_position_beyond_size() {
    mmr_proof::verify_with_root(ROOT_13, 23, 24, b"1", vector[], vector[], vector[]);
}

#[test, expected_failure(abort_code = mmr_proof::EPositionOutOfRange)]
fun single_rejects_any_position_on_empty_mmr() {
    mmr_proof::verify_with_root(ROOT_0, 0, 1, b"1", vector[], vector[], vector[]);
}

#[test, expected_failure(abort_code = mmr_proof::ENotALeaf)]
fun single_rejects_internal_node() {
    // A2 forgery shape: position 3 with data = n1 || n2 and the honest siblings of node 3
    let ns = mmr_prover::build(13);
    let mut data = ns.node(1);
    data.append(ns.node(2));
    mmr_proof::verify_with_root(ROOT_13, 23, 3, data, vector[ns.node(6), ns.node(14)], vector[], vector[N22, N23]);
}

#[test, expected_failure(abort_code = mmr_proof::ENotALeaf)]
fun single_rejects_peak_as_position() {
    // the peak 15 as the position, with data = n7 || n14 and the other two peaks
    let ns = mmr_prover::build(13);
    let mut data = ns.node(7);
    data.append(ns.node(14));
    mmr_proof::verify_with_root(ROOT_13, 23, 15, data, vector[], vector[], vector[N22, N23]);
}

#[test, expected_failure(abort_code = mmr_proof::EPathLength)]
fun single_rejects_short_path() {
    let ns = mmr_prover::build(13);
    let (mut path, left, right) = ns.single_proof(16);
    path.pop_back();
    mmr_proof::verify_with_root(ROOT_13, 23, 16, b"9", path, left, right);
}

#[test, expected_failure(abort_code = mmr_proof::EPathLength)]
fun single_rejects_long_path() {
    // trailing junk was accepted by v1
    let ns = mmr_prover::build(13);
    let (mut path, left, right) = ns.single_proof(16);
    path.push_back(N3);
    mmr_proof::verify_with_root(ROOT_13, 23, 16, b"9", path, left, right);
}

#[test, expected_failure(abort_code = mmr_proof::EPathLength)]
fun single_rejects_path_for_peak_leaf() {
    // leaf 23 is a peak: its path is empty
    mmr_proof::verify_with_root(ROOT_13, 23, 23, b"13", vector[N22], vector[N15, N22], vector[]);
}

#[test, expected_failure(abort_code = mmr_proof::EPeaksCount)]
fun single_rejects_wrong_peak_count() {
    // missing left peak
    let ns = mmr_prover::build(13);
    let (path, _left, right) = ns.single_proof(16);
    mmr_proof::verify_with_root(ROOT_13, 23, 16, b"9", path, vector[], right);
}

#[test, expected_failure(abort_code = mmr_proof::EPeaksCount)]
fun single_rejects_wrong_right_peak_count() {
    // one right peak too many
    let ns = mmr_prover::build(13);
    let (path, left, mut right) = ns.single_proof(16);
    right.push_back(N23);
    mmr_proof::verify_with_root(ROOT_13, 23, 16, b"9", path, left, right);
}

#[test, expected_failure(abort_code = mmr_proof::EPeaksCount)]
fun single_rejects_peaks_moved_to_the_other_side() {
    // both peaks on the left: same total, wrong split
    mmr_proof::verify_with_root(ROOT_13, 23, 16, b"9", vector[N17, N21], vector[N15, N23], vector[]);
}

/// Two supplied peak slots merged into one 64-byte element: the count check fires first.
#[test, expected_failure(abort_code = mmr_proof::EPeaksCount)]
fun single_rejects_merged_peak_slots() {
    let mut merged = N22;
    merged.append(N23);
    mmr_proof::verify_with_root(ROOT_13, 23, 1, b"1", vector[N2, N6, N14], vector[], vector[merged]);
}

#[test, expected_failure(abort_code = mmr_proof::EHashLength)]
fun single_rejects_short_hash() {
    // 31-byte hash in the path
    let ns = mmr_prover::build(13);
    let (mut path, left, right) = ns.single_proof(16);
    let mut short = path.pop_back();
    short.pop_back();
    path.push_back(short);
    mmr_proof::verify_with_root(ROOT_13, 23, 16, b"9", path, left, right);
}

#[test, expected_failure(abort_code = mmr_proof::EHashLength)]
fun single_rejects_long_hash() {
    // 33-byte hash in the right peaks
    let ns = mmr_prover::build(13);
    let (path, left, mut right) = ns.single_proof(16);
    let mut long = right.pop_back();
    long.push_back(0);
    right.push_back(long);
    mmr_proof::verify_with_root(ROOT_13, 23, 16, b"9", path, left, right);
}

// ------------------------------------------------------------------------------ aborts (batch)

#[test, expected_failure(abort_code = mmr_proof::EEmptyBatch)]
fun batch_rejects_empty() {
    mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[], vector[], vector[], vector[N15, N22, N23]);
}

#[test, expected_failure(abort_code = mmr_proof::ELengthMismatch)]
fun batch_rejects_length_mismatch() {
    mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[1], vector[], vector[], vector[]);
}

#[test, expected_failure(abort_code = mmr_proof::EPositionsNotSorted)]
fun batch_rejects_duplicates() {
    mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[4, 4], vector[b"3", b"x"], vector[], vector[]);
}

#[test, expected_failure(abort_code = mmr_proof::EPositionsNotSorted)]
fun batch_rejects_unsorted() {
    mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[9, 4], vector[b"6", b"3"], vector[], vector[]);
}

#[test, expected_failure(abort_code = mmr_proof::EPositionsNotSorted)]
fun batch_rejects_position_zero() {
    mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[0], vector[b"x"], vector[], vector[]);
}

#[test, expected_failure(abort_code = mmr_proof::EPositionOutOfRange)]
fun batch_rejects_position_beyond_size() {
    mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[24], vector[b"x"], vector[], vector[]);
}

#[test, expected_failure(abort_code = mmr_proof::ENotALeaf)]
fun batch_rejects_internal_node() {
    mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[3], vector[b"x"], vector[], vector[]);
}

#[test, expected_failure(abort_code = mmr_proof::EInvalidSize)]
fun batch_rejects_invalid_size() {
    mmr_proof::verify_multiple_with_root(ROOT_13, 24, vector[1], vector[b"1"], vector[], vector[]);
}

#[test, expected_failure(abort_code = mmr_proof::EMissingProofHashes)]
fun batch_rejects_missing_siblings() {
    let ns = mmr_prover::build(13);
    let (mut siblings, untouched) = ns.batch_proof(vector[4, 9, 16]);
    siblings.pop_back();
    mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[4, 9, 16], vector[b"3", b"6", b"9"], siblings, untouched);
}

#[test, expected_failure(abort_code = mmr_proof::EMissingProofHashes)]
fun batch_rejects_missing_untouched_peak() {
    let ns = mmr_prover::build(13);
    let (siblings, _untouched) = ns.batch_proof(vector[4, 9, 16]);
    mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[4, 9, 16], vector[b"3", b"6", b"9"], siblings, vector[]);
}

/// A sibling moved into the untouched-peak vector: the sibling cursor runs dry first.
#[test, expected_failure(abort_code = mmr_proof::EMissingProofHashes)]
fun batch_rejects_sibling_supplied_as_peak() {
    mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[16], vector[b"9"], vector[N17], vector[N15, N21, N23]);
}

#[test, expected_failure(abort_code = mmr_proof::ELeftoverProofHashes)]
fun batch_rejects_extra_sibling() {
    let ns = mmr_prover::build(13);
    let (mut siblings, untouched) = ns.batch_proof(vector[4, 9, 16]);
    siblings.push_back(N3);
    mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[4, 9, 16], vector[b"3", b"6", b"9"], siblings, untouched);
}

#[test, expected_failure(abort_code = mmr_proof::ELeftoverProofHashes)]
fun batch_rejects_extra_untouched_peak() {
    let ns = mmr_prover::build(13);
    let (siblings, mut untouched) = ns.batch_proof(vector[4, 9, 16]);
    untouched.push_back(N23);
    mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[4, 9, 16], vector[b"3", b"6", b"9"], siblings, untouched);
}

#[test, expected_failure(abort_code = mmr_proof::EHashLength)]
fun batch_rejects_short_hash() {
    let ns = mmr_prover::build(13);
    let (siblings, mut untouched) = ns.batch_proof(vector[4, 9, 16]);
    let mut short = untouched.pop_back();
    short.pop_back();
    untouched.push_back(short);
    mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[4, 9, 16], vector[b"3", b"6", b"9"], siblings, untouched);
}

// ------------------------------------------------------------------------------ check order
// The first failing check names the abort (spec F.3 / F.4 order).

/// Position range is checked before the leaf check and before any path math (30 is an
/// internal-node position beyond the size).
#[test, expected_failure(abort_code = mmr_proof::EPositionOutOfRange)]
fun single_check_order_range_before_leaf() {
    mmr_proof::verify_with_root(ROOT_13, 23, 30, b"x", vector[], vector[], vector[]);
}

/// The leaf check runs before the path length check.
#[test, expected_failure(abort_code = mmr_proof::ENotALeaf)]
fun single_check_order_leaf_before_path_length() {
    mmr_proof::verify_with_root(ROOT_13, 23, 3, b"x", vector[], vector[], vector[]);
}

/// The path length check runs before the peaks count check.
#[test, expected_failure(abort_code = mmr_proof::EPathLength)]
fun single_check_order_path_before_peaks() {
    mmr_proof::verify_with_root(ROOT_13, 23, 16, b"9", vector[], vector[], vector[]);
}

/// The peaks count check runs before the hash length check.
#[test, expected_failure(abort_code = mmr_proof::EPeaksCount)]
fun single_check_order_peaks_before_hash_length() {
    mmr_proof::verify_with_root(ROOT_13, 23, 16, b"9", vector[b"a", b"b"], vector[], vector[]);
}

/// Sortedness is checked before the range of a later position.
#[test, expected_failure(abort_code = mmr_proof::EPositionsNotSorted)]
fun batch_check_order_sorted_before_range() {
    mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[4, 4, 99], vector[b"a", b"b", b"c"], vector[], vector[]);
}

/// Hash lengths are checked before the traversal reads anything.
#[test, expected_failure(abort_code = mmr_proof::EHashLength)]
fun batch_check_order_hash_length_before_traversal() {
    mmr_proof::verify_multiple_with_root(ROOT_13, 23, vector[1], vector[b"1"], vector[b"short"], vector[]);
}
