#!/usr/bin/env python3
"""Golden vectors for the Sui `mmr` package test suite.

Prints, from the Python reference in `mmr_ref.py`:

  1. the roots table: leaves "1".."N" (ASCII decimal) -> size, peak positions, root;
  2. every node hash of the README MMR (13 leaves, size 23);
  3. the six worked batch proofs on the README MMR, in consumption order.

Usage (`--help` prints the same):
    python3 scripts/golden.py                      # print the vectors
    python3 scripts/golden.py --move               # print them as a ready-to-paste Move
                                                   # `const` block (ROOT_<n>, N<p>)
    python3 scripts/golden.py --check [MOVE_FILE ...]
                                                   # exit 1 if any pinned constant drifted;
                                                   # default: the four test files below

The `--check` mode reads every `const ROOT_<n>` / `const N<p>` hex literal in the given Move
test files (default: `CHECK_FILES`) and compares it with the freshly computed value, so the
vectors cannot drift. It reports the pinned count per file and, for information, the reference
names no file pins.
"""
from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import mmr_ref  # noqa: E402

ROOT_CASES = [0, 1, 2, 3, 4, 7, 8, 13, 95, 128, 200, 255, 256, 511, 512, 1000, 1023, 1024]
README_LEAVES = 13
# Test files that pin golden constants (relative to the package root, `sui/`).
CHECK_FILES = [
    "tests/mmr_proof_tests.move",
    "tests/mmr_tests.move",
    "tests/mmr_utils_tests.move",
    "tests/mmr_adversarial_tests.move",
]
README_BATCHES = [[1], [16], [1, 2], [4, 9, 16], [23], [1, 2, 4, 5, 8, 9, 11, 12, 16, 17, 19, 20, 23]]


def roots_table() -> dict[int, tuple[int, list[int], bytes]]:
    """leaves -> (size, peak positions, root)."""
    table = {}
    ns = mmr_ref.NodeSet()
    table[0] = (0, [], ns.root())
    for n in range(1, max(ROOT_CASES) + 1):
        ns.append(mmr_ref.leaf_data(n))
        if n in ROOT_CASES:
            table[n] = (ns.size, ns.peaks_positions(), ns.root())
    return table


def readme_batches(ns: mmr_ref.NodeSet) -> list[tuple[list[int], list[str], list[str]]]:
    """(positions, sibling labels, untouched labels) for the six worked examples."""
    label = {ns.node(p): f"n{p}" for p in range(1, ns.size + 1)}
    out = []
    for batch in README_BATCHES:
        siblings, untouched = ns.batch_proof(batch)
        data = [mmr_ref.leaf_data(mmr_ref.position_to_leaf_index(p) + 1) for p in batch]
        assert mmr_ref.verify_batch(ns.root(), ns.size, batch, data, siblings, untouched)
        out.append((batch, [label[h] for h in siblings], [label[h] for h in untouched]))
    return out


def print_vectors() -> None:
    table = roots_table()
    print("# roots: leaves \"1\"..\"N\", root = H(enc(size) || peaks)")
    print(f"{'leaves':>6} {'size':>5}  {'peaks':<52} root")
    for n in ROOT_CASES:
        size, peaks, root = table[n]
        print(f"{n:>6} {size:>5}  {str(peaks):<52} {root.hex()}")
    ns = mmr_ref.build(README_LEAVES)
    print()
    print("# README MMR (13 leaves, size 23): node hashes")
    for p in range(1, ns.size + 1):
        print(f"n{p:<3} {ns.node(p).hex()}")
    print()
    print("# README MMR: single proof for position 16 (leaf \"9\")")
    path, left, right = ns.single_proof(16)
    label = {ns.node(p): f"n{p}" for p in range(1, ns.size + 1)}
    print(f"path={[label[h] for h in path]} left={[label[h] for h in left]} right={[label[h] for h in right]}")
    print()
    print("# README MMR: batch proofs (siblings in consumption order; untouched peaks left to right)")
    for batch, siblings, untouched in readme_batches(ns):
        print(f"{str(batch):<50} siblings={siblings} untouched={untouched}")


def print_move() -> None:
    """The pinned values as a Move `const` block (paste into tests/mmr_proof_tests.move)."""
    table = roots_table()
    ns = mmr_ref.build(README_LEAVES)
    print("// Golden values (blake2b-256; generated by `scripts/golden.py --move`).")
    for n in ROOT_CASES:
        print(f'const ROOT_{n}: vector<u8> = x"{table[n][2].hex()}";')
    print()
    print("// README MMR (13 leaves, size 23) node hashes, `nX` = node at position X.")
    for p in range(1, ns.size + 1):
        print(f'const N{p}: vector<u8> = x"{ns.node(p).hex()}";')


def reference_values() -> dict[str, str]:
    """Every golden name (`ROOT_<n>`, `N<p>`) -> hex value, from the reference."""
    expected = {}
    for n, (_, _, root) in roots_table().items():
        expected[f"ROOT_{n}"] = root.hex()
    ns = mmr_ref.build(README_LEAVES)
    for p in range(1, ns.size + 1):
        expected[f"N{p}"] = ns.node(p).hex()
    return expected


def check(move_files: list[str]) -> int:
    """Compare every `const ROOT_<n>` / `const N<p>` in `move_files` with the reference.

    Exit status 1 when a constant drifted, is unknown to the reference, or a file pins nothing;
    the list of reference names no file pins is informational."""
    expected = reference_values()
    seen: set[str] = set()
    failed = False
    for move_file in move_files:
        src = open(move_file).read()
        pinned = re.findall(r'const\s+(ROOT_\w+|N\d+)\s*:\s*vector<u8>\s*=\s*x"([0-9a-fA-F]+)"', src)
        if not pinned:
            print(f"{move_file}: no pinned constants found")
            failed = True
            continue
        drift = 0
        for name, value in pinned:
            seen.add(name)
            if name not in expected:
                print(f"UNKNOWN {name} in {move_file}")
                drift += 1
            elif expected[name] != value.lower():
                print(f"DRIFT   {name} in {move_file}: pinned {value} expected {expected[name]}")
                drift += 1
        print(f"{move_file}: {len(pinned)} pinned constants checked, {drift} drifted")
        failed = failed or drift > 0
    unpinned = [name for name in expected if name not in seen]
    print(f"reference names not pinned by any file ({len(unpinned)}): {' '.join(unpinned) or '-'}")
    return 1 if failed else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="golden.py",
        description="Golden vectors for the Sui `mmr` package test suite, computed by the "
                    "Python reference in mmr_ref.py. Without flags: print the table.",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--move", action="store_true",
                      help="print the values as a ready-to-paste Move `const` block (ROOT_<n>, N<p>)")
    mode.add_argument("--check", metavar="MOVE_FILE", nargs="*",
                      help="compare every pinned `const ROOT_<n>` / `const N<p>` in each MOVE_FILE "
                           "with the reference (default: " + ", ".join(CHECK_FILES) + "); "
                           "exit 1 on drift")
    args = parser.parse_args(argv)
    if args.check is not None:
        return check(args.check or CHECK_FILES)
    if args.move:
        print_move()
    else:
        print_vectors()
    return 0


if __name__ == "__main__":
    sys.exit(main())
